author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule)
category: process_creation
date: 2021/08/23
description: Initial execution of malicious document calls wmic to execute the file
  with regsvr32
detection:
  condition: selection1 and selection2
  selection1:
  - winlog.event_data.Image: \wbem\WMIC.exe
  - winlog.event_data.CommandLine|contains: 'wmic '
  - winlog.event_data.OriginalFileName: wmic.exe
  - winlog.event_data.Description: WMI Commandline Utility
  selection2:
    ParentPrcessName|endswith:
    - winword.exe
    - excel.exe
    - powerpnt.exe
falsepositives:
- Unknown
id: 518643ba-7d9c-4fa5-9f37-baed36059f6a
level: high
logsource:
  category: process_creation
  product: windows
product: windows
references:
- https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
- https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
status: experimental
tags:
- attack.t1204.002
- attack.t1047
- attack.t1218.010
- attack.execution
- attack.defense_evasion
title: Office Applications Spawning Wmi Cli
