author: frack113
category: process_creation
date: 2022/08/19
description: Detect malicious GPO modifications can be used to implement many other
  malicious behaviors.
detection:
  condition: all of selection_*
  selection_key:
    winlog.event_data.CommandLine|contains:
    - GroupPolicyRefreshTimeDC
    - GroupPolicyRefreshTimeOffsetDC
    - GroupPolicyRefreshTime
    - GroupPolicyRefreshTimeOffset
    - EnableSmartScreen
    - ShellSmartScreenLevel
  selection_path:
    winlog.event_data.CommandLine|contains: \SOFTWARE\Policies\Microsoft\Windows\System
  selection_reg:
  - winlog.event_data.Image|endswith: \reg.exe
  - winlog.event_data.OriginalFileName: reg.exe
falsepositives:
- Legitimate use
id: ada4b0c4-758b-46ac-9033-9004613a150d
level: medium
logsource:
  category: process_creation
  product: windows
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/40b77d63808dd4f4eafb83949805636735a1fd15/atomics/T1484.001/T1484.001.md
related:
- id: b7216a7d-687e-4c8d-82b1-3080b2ad961f
  type: similar
status: experimental
tags:
- attack.defense_evasion
- attack.privilege_escalation
- attack.t1484.001
title: Modify Group Policy Settings
