author: Nasreddine Bencherchali
category: process_creation
date: 2022/08/19
description: Detects the execution of DeviceCredentialDeployment to hide a process
  from view
detection:
  condition: selection
  selection:
    winlog.event_data.Image|endswith: \DeviceCredentialDeployment.exe
falsepositives:
- Unlikely
id: b8b1b304-a60f-4999-9a6e-c547bde03ffd
level: medium
logsource:
  category: process_creation
  product: windows
product: windows
references:
- https://github.com/LOLBAS-Project/LOLBAS/pull/147
status: experimental
tags:
- attack.defense_evasion
- attack.t1218
title: DeviceCredentialDeployment Execution
