author: Anton Kutepov, oscd.community
category: process_creation
date: 2020/02/05
description: Detects using SettingSyncHost.exe to run hijacked binary
detection:
  condition: not system_utility and parent_is_settingsynchost
  parent_is_settingsynchost:
    winlog.event_data.ParentCommandLine|contains|all:
    - cmd.exe /c
    - RoamDiag.cmd
    - -outputpath
  system_utility:
    winlog.event_data.Image|startswith:
    - C:\Windows\System32\
    - C:\Windows\SysWOW64\
falsepositives:
- Unknown
fields:
- winlog.event_data.TargetFilename
- winlog.event_data.Image
id: b2ddd389-f676-4ac4-845a-e00781a48e5f
level: high
logsource:
  category: process_creation
  product: windows
modified: 2021/11/27
product: windows
references:
- https://www.hexacorn.com/blog/2020/02/02/settingsynchost-exe-as-a-lolbin
status: test
tags:
- attack.execution
- attack.defense_evasion
- attack.t1574.008
title: Using SettingSyncHost.exe as LOLBin
