author: frack113
category: process_creation
date: 2021/11/26
description: Upload file, credentials or data exfiltration with Binary part of Windows
  Defender
detection:
  condition: lolbas and remote
  lolbas:
  - winlog.event_data.CommandLine|contains: ConfigSecurityPolicy.exe
  - winlog.event_data.Image|endswith: \ConfigSecurityPolicy.exe
  - winlog.event_data.OriginalFileName: ConfigSecurityPolicy.exe
  remote:
    winlog.event_data.CommandLine|contains:
    - https://
    - http://
    - ftp://
falsepositives:
- Unknown
id: 1f0f6176-6482-4027-b151-00071af39d7e
level: medium
logsource:
  category: process_creation
  product: windows
modified: 2022/05/16
product: windows
references:
- https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
status: experimental
tags:
- attack.exfiltration
- attack.t1567
title: Suspicious ConfigSecurityPolicy Execution
