author: frac113
category: process_creation
date: 2022/01/28
description: Uninstall an application with wmic
detection:
  condition: all of selection*
  selection_cli:
    winlog.event_data.CommandLine|contains: call uninstall
  selection_img:
  - winlog.event_data.Image|endswith: \WMIC.exe
  - winlog.event_data.OriginalFileName: wmic.exe
falsepositives:
- Unknown
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
level: medium
logsource:
  category: process_creation
  product: windows
modified: 2022/05/13
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
status: experimental
tags:
- attack.execution
- attack.t1047
title: WMI Uninstall An Application
