author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule), Michael Haag
category: process_creation
date: 2021/08/23
description: This rule will monitor any office apps that spins up a new LOLBin process.
  This activity is pretty suspicious and should be investigated.
detection:
  condition: selection
  selection:
    winlog.event_data.Image|endswith:
    - \regsvr32.exe
    - \rundll32.exe
    - \msiexec.exe
    - \mshta.exe
    - \verclsid.exe
    - \msdt.exe
    - \control.exe
    winlog.event_data.ParentImage|endswith:
    - \winword.exe
    - \excel.exe
    - \powerpnt.exe
    - \msaccess.exe
    - \mspub.exe
    - \eqnedt32.exe
    - \visio.exe
    - \wordpad.exe
    - \wordview.exe
falsepositives:
- Unknown
id: 23daeb52-e6eb-493c-8607-c4f0246cb7d8
level: high
logsource:
  category: process_creation
  product: windows
modified: 2022/07/20
product: windows
references:
- https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
- https://doublepulsar.com/follina-a-microsoft-office-code-execution-vulnerability-1a47fce5629e
- https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/02bcbfc2bfb8b4da601bb30de0344ae453aa1afe/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
- https://github.com/splunk/security_content/blob/develop/detections/endpoint/office_spawning_control.yml
status: experimental
tags:
- attack.t1204.002
- attack.t1047
- attack.t1218.010
- attack.execution
- attack.defense_evasion
title: New Lolbin Process by Office Applications
