author: Timur Zinniatullin, oscd.community
date: 2020/10/18
description: Detects Obfuscated Powershell via RUNDLL LAUNCHER
detection:
  condition: selection
  selection:
    winlog.event_data.ServiceFileName|contains|all:
    - rundll32.exe
    - shell32.dll
    - shellexec_rundll
    - powershell
    winlog.event_id: 4697
falsepositives:
- Unknown
id: f241cf1b-3a6b-4e1a-b4f9-133c00dd95ca
level: medium
logsource:
  product: windows
  service: security
modified: 2022/03/06
product: windows
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 11b52f18-aaec-4d60-9143-5dd8cc4706b9
  type: derived
service: security
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation RUNDLL LAUNCHER
