author: Nikita Nazarov, oscd.community
date: 2020/10/09
description: Detects Obfuscated Powershell via use Rundll32 in Scripts
detection:
  condition: selection
  selection:
    winlog.event_data.ServiceFileName|contains:
    - value
    - invoke
    - comspec
    - iex
    winlog.event_data.ServiceFileName|contains|all:
    - '&&'
    - rundll32
    - shell32.dll
    - shellexec_rundll
    winlog.event_id: 4697
falsepositives:
- Unknown
id: cd0f7229-d16f-42de-8fe3-fba365fbcb3a
level: high
logsource:
  product: windows
  service: security
modified: 2022/03/06
product: windows
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 641a4bfb-c017-44f7-800c-2aee0184ce9b
  type: derived
service: security
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation Via Use Rundll32
