author: Orlinum , BlueDefenZer
date: 2021/11/17
definition: Certificate services loaded a template would trigger event ID 4898 and
  certificate Services template was updated would trigger event ID 4899. A risk permission
  seems to be coming if template contain specific flag with risky EKU.
description: Detects certificate creation with template allowing risk permission subject
  and risky EKU
detection:
  condition: (selection10 and selection11) or (selection20 and selection21)
  selection10:
    TemplateContent|contains:
    - 1.3.6.1.5.5.7.3.2
    - 1.3.6.1.5.2.3.4
    - 1.3.6.1.4.1.311.20.2.2
    - 2.5.29.37.0
    winlog.event_id: 4898
  selection11:
    TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
  selection20:
    NewTemplateContent|contains:
    - 1.3.6.1.5.5.7.3.2
    - 1.3.6.1.5.2.3.4
    - 1.3.6.1.4.1.311.20.2.2
    - 2.5.29.37.0
    winlog.event_id: 4899
  selection21:
    NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
falsepositives:
- Administrator activity
- Proxy SSL certificate with subject modification
- Smart card enrollement
id: bfbd3291-de87-4b7c-88a2-d6a5deb28668
level: high
logsource:
  definition: Certificate services loaded a template would trigger event ID 4898 and
    certificate Services template was updated would trigger event ID 4899. A risk
    permission seems to be coming if template contain specific flag with risky EKU.
  product: windows
  service: security
product: windows
references:
- https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
service: security
status: experimental
tags:
- attack.privilege_escalation
- attack.credential_access
title: ADCS Certificate Template Configuration Vulnerability with Risky EKU
