author: Timur Zinniatullin, oscd.community
date: 2020/10/13
description: Detects Obfuscated Powershell via VAR++ LAUNCHER
detection:
  condition: selection
  selection:
    winlog.event_data.ServiceFileName|re: (?i).*&&set.*(\{\d\}){2,}\\\"\s+?\-f.*&&.*cmd.*\/c
    winlog.event_id: 4697
falsepositives:
- Unknown
id: 4c54ba8f-73d2-4d40-8890-d9cf1dca3d30
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/18
product: windows
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 14bcba49-a428-42d9-b943-e2ce0f0f7ae6
  type: derived
service: security
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION
