author: Orlinum , BlueDefenZer
date: 2021/11/17
definition: Certificate services loaded a template would trigger event ID 4898 and
  certificate Services template was updated would trigger event ID 4899. A risk permission
  seems to be coming if template contain specific flag.
description: Detects certificate creation with template allowing risk permission subject
detection:
  condition: selection1 or selection2
  selection1:
    TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    winlog.event_id: 4898
  selection2:
    NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    winlog.event_id: 4899
falsepositives:
- Administrator activity
- Proxy SSL certificate with subject modification
- Smart card enrollement
id: 5ee3a654-372f-11ec-8d3d-0242ac130003
level: low
logsource:
  definition: Certificate services loaded a template would trigger event ID 4898 and
    certificate Services template was updated would trigger event ID 4899. A risk
    permission seems to be coming if template contain specific flag.
  product: windows
  service: security
product: windows
references:
- https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
service: security
status: experimental
tags:
- attack.privilege_escalation
- attack.credential_access
title: ADCS Certificate Template Configuration Vulnerability
