author: Timur Zinniatullin, oscd.community
date: 2020/10/18
description: Detects Obfuscated Powershell via COMPRESS OBFUSCATION
detection:
  condition: all of selection*
  selection:
    winlog.event_data.ServiceFileName|contains|all:
    - new-object
    - text.encoding]::ascii
    - readtoend
    winlog.event_id: 4697
  selection2:
    winlog.event_data.ServiceFileName|contains:
    - system.io.compression.deflatestream
    - system.io.streamreader
falsepositives:
- Unknown
id: 7a922f1b-2635-4d6c-91ef-af228b198ad3
level: medium
logsource:
  product: windows
  service: security
modified: 2022/02/03
product: windows
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 175997c5-803c-4b08-8bb0-70b099f47595
  type: derived
service: security
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation COMPRESS OBFUSCATION
