author: Nikita Nazarov, oscd.community
date: 2020/10/09
description: Detects Obfuscated Powershell via use Clip.exe in Scripts
detection:
  condition: selection
  selection:
    winlog.event_data.ServiceFileName|contains: (Clipboard|i
    winlog.event_id: 4697
falsepositives:
- Unknown
id: 1a0a2ff1-611b-4dac-8216-8a7b47c618a6
level: high
logsource:
  product: windows
  service: security
modified: 2022/04/26
product: windows
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 63e3365d-4824-42d8-8b82-e56810fefa0c
  type: derived
service: security
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation Via Use Clip
