author: frack113
date: 2022/01/28
description: An application have been remove check if it is a critical
detection:
  condition: selection
  selection:
    Provider_Name: MsiInstaller
    winlog.event_id:
    - 11724
    - 1034
falsepositives:
- Unknown
id: 570ae5ec-33dc-427c-b815-db86228ad43e
level: low
logsource:
  product: windows
  service: application
product: windows
service: application
status: experimental
tags:
- attack.impact
- attack.t1489
title: An Application Is Uninstall
