author: frack113
category: registry_set
date: 2021/12/28
description: Change outlook email security settings
detection:
  condition: selection
  selection:
    winlog.event_data.EventType: SetValue
    winlog.event_data.TargetObject|contains|all:
    - \SOFTWARE\Microsoft\Office\
    - \Outlook\Security\
falsepositives:
- Administrative scripts
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
level: medium
logsource:
  category: registry_set
  product: windows
modified: 2022/03/26
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1137/T1137.md
- https://docs.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
status: experimental
tags:
- attack.persistence
- attack.t1137
title: Change Outlook Security Setting in Registry
