author: frack113
category: sysmon_error
date: 2021/06/04
description: Detects when an adversary is trying to hide it's action from Sysmon logging
  based on error messages
detection:
  condition: selection_error and not 1 of filter*
  filter_by_errorcode:
    winlog.event_data.Description|contains:
    - Failed to open service configuration with error 19
    - Failed to open service configuration with error 93
  filter_generic_english:
    winlog.event_data.Description|contains|all:
    - Failed to open service configuration with error
    - 'Last error: The media is write protected.'
  selection_error:
    winlog.event_data.Description|contains:
    - Failed to open service configuration with error
    - Failed to connect to the driver to update configuration
falsepositives:
- Legitimate administrative action
id: 815cd91b-7dbc-4247-841a-d7dd1392b0a8
level: high
logsource:
  category: sysmon_error
  product: windows
modified: 2022/07/07
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
status: experimental
tags:
- attack.defense_evasion
- attack.t1564
title: Sysmon Configuration Error
