author: frack113
category: sysmon_status
date: 2021/06/04
description: Detects when an attacker tries to hide from Sysmon by disabling or stopping
  it
detection:
  condition: 1 of selection_* and not filter
  filter:
    winlog.event_data.State: Started
  selection_conf:
  - Sysmon config state changed
  selection_stop:
    winlog.event_data.State: Stopped
falsepositives:
- Legitimate administrative action
id: 1f2b5353-573f-4880-8e33-7d04dcf97744
level: high
logsource:
  category: sysmon_status
  product: windows
modified: 2022/08/02
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
status: test
tags:
- attack.defense_evasion
- attack.t1564
title: Sysmon Configuration Modification
