author: frack113
category: sysmon_error
date: 2021/06/04
description: Someone try to hide from Sysmon
detection:
  condition: selection_error
  selection_error:
    winlog.event_data.Description|contains:
    - Failed to open service configuration with error
    - Failed to connect to the driver to update configuration
falsepositives:
- legitimate administrative action
id: 815cd91b-7dbc-4247-841a-d7dd1392b0a8
level: high
logsource:
  category: sysmon_error
  product: windows
modified: 2021/09/07
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
status: experimental
tags:
- attack.defense_evasion
- attack.t1564
title: Sysmon Configuration Error
