author: frack113
date: 2022/01/12
description: Detects a Sysmon configuration change, which could be the result of a
  legitimate reconfiguration or someone trying manipulate the configuration
detection:
  condition: selection
  selection:
    winlog.event_id: 16
falsepositives:
- Legitimate administrative action
id: 8ac03a65-6c84-4116-acad-dc1558ff7a77
level: medium
logsource:
  product: windows
  service: sysmon
product: windows
references:
- https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon
service: sysmon
status: experimental
tags:
- attack.defense_evasion
title: Sysmon Configuration Change
