author: Tim Shelton
date: 2022/04/26
description: Detects application popup reporting a failure of the Sysmon service
detection:
  condition: selection
  selection:
    Caption: sysmon64.exe - Application Error
    Provider_Name: Application Popup
    winlog.event_id: 26
falsepositives:
- Unknown
id: 4d7f1827-1637-4def-8d8a-fd254f9454df
level: high
logsource:
  product: windows
  service: system
product: windows
service: system
status: experimental
tags:
- attack.t1562
- attack.impair_defenses
title: Sysmon Crash
