author: Austin Songer @austinsonger
date: 2021/09/03
description: Identifies when a owner is was removed from a application or service
  principal in Azure.
detection:
  condition: selection
  selection:
    properties.message:
    - Remove owner from service principal
    - Remove owner from application
falsepositives:
- Owner being removed may be performed by a system administrator.
- Verify whether the user identity, user agent, and/or hostname should be making changes
  in your environment.
- Owner removed from unfamiliar users should be investigated. If known behavior is
  causing false positives, it can be exempted from the rule.
id: 636e30d5-3736-42ea-96b1-e6e2f8429fd6
level: medium
logsource:
  service: azure.activitylogs
references:
- https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-audit-activities#application-proxy
service: azure.activitylogs
status: experimental
tags:
- attack.defense_evasion
title: Azure Owner Removed From Application or Service Principal
