action: global
author: frack113
date: 2021/06/04
description: Someone try to hide from Sysmon
falsepositives:
- legitimate administrative action
id: 47b99f35-413c-473f-854c-2c5085fb31c8
level: high
modified: 2021/06/16
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
status: experimental
tags:
- attack.defense_evasion
- attack.t1564
title: Sysmon Configuration Modification
