category: sysmon_error
detection:
  condition: selection_error
  selection_error:
    winlog.event_data.Description|contains:
    - Failed to open service configuration with error
    - Failed to connect to the driver to update configuration
id: 815cd91b-7dbc-4247-841a-d7dd1392b0a8
logsource:
  category: sysmon_error
  product: windows
product: windows
