category: sysmon_status
detection:
  condition: selection_stop or selection_conf
  selection_conf:
  - Sysmon config state changed
  selection_stop:
    winlog.event_data.State: Stopped
id: 1f2b5353-573f-4880-8e33-7d04dcf97744
logsource:
  category: sysmon_status
  product: windows
product: windows
