author: Austin Songer @austinsonger
date: 2021/09/03
description: Identifies when a device or device configuration in azure is modified
  or deleted.
detection:
  condition: selection
  selection:
    properties.message:
    - Delete device
    - Delete device configuration
    - Update device
    - Update device configuration
falsepositives:
- Device or device configuration being modified or deleted may be performed by a system
  administrator.
- Verify whether the user identity, user agent, and/or hostname should be making changes
  in your environment.
- Device or device configuration modified or deleted from unfamiliar users should
  be investigated. If known behavior is causing false positives, it can be exempted
  from the rule.
id: 46530378-f9db-4af9-a9e5-889c177d3881
level: medium
logsource:
  product: azure
  service: activitylogs
product: azure
references:
- https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-audit-activities#core-directory
service: activitylogs
status: experimental
tags:
- attack.impact
title: Azure Device or Configuration Modified or Deleted
