author: Mark Morowczynski '@markmorow', Yochana Henderson, '@Yochana-H'
date: 2022/08/09
description: Detects when changes are made to PIM roles
detection:
  condition: selection
  selection:
    properties.message: Update role setting in PIM
falsepositives:
- Legit administrative PIM setting configuration changes
id: db6c06c4-bf3b-421c-aa88-15672b88c743
level: high
logsource:
  product: azure
  service: auditlogs
product: azure
references:
- https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/security-operations-privileged-identity-management#azure-ad-roles-assignment
service: auditlogs
status: experimental
tags:
- attack.privilege_escalation
- attack.defense_evasion
- attack.t1078
title: Changes To PIM Settings
