author: Austin Songer
date: 2021/08/16
description: Identifies when a application gateway is modified or deleted.
detection:
  condition: selection
  selection:
    operationName:
    - MICROSOFT.NETWORK/APPLICATIONGATEWAYS/WRITE
    - MICROSOFT.NETWORK/APPLICATIONGATEWAYS/DELETE
falsepositives:
- Application gateway being modified or deleted may be performed by a system administrator.
- Verify whether the user identity, user agent, and/or hostname should be making changes
  in your environment.
- Application gateway modified or deleted from unfamiliar users should be investigated.
  If known behavior is causing false positives, it can be exempted from the rule.
id: ad87d14e-7599-4633-ba81-aeb60cfe8cd6
level: medium
logsource:
  product: azure
  service: activitylogs
modified: 2022/08/23
product: azure
references:
- https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations
service: activitylogs
status: experimental
tags:
- attack.impact
title: Azure Application Gateway Modified or Deleted
