author: Austin Songer
date: 2021/08/26
description: Detects when an an application is removed from Google Workspace.
detection:
  condition: selection
  selection:
    eventName:
    - REMOVE_APPLICATION
    - REMOVE_APPLICATION_FROM_WHITELIST
    eventService: admin.googleapis.com
falsepositives:
- Application being removed may be performed by a System Administrator.
id: ee2803f0-71c8-4831-b48b-a1fc57601ee4
level: medium
logsource:
  service: google_workspace.admin
references:
- https://cloud.google.com/logging/docs/audit/gsuite-audit-logging#3
- https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-domain-settings?hl=en#REMOVE_APPLICATION
- https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-domain-settings?hl=en#REMOVE_APPLICATION_FROM_WHITELIST
service: google_workspace.admin
status: experimental
tags:
- attack.impact
title: Google Workspace Application Removed
