author: Florian Roth
date: 2017/05/08
description: This rule detects a DNS server error in which a specified plugin DLL
  (in registry) could not be loaded
detection:
  condition: selection
  selection:
    winlog.event_id:
    - 150
    - 770
falsepositives:
- Unknown
id: cbe51394-cd93-4473-b555-edf0144952d9
level: critical
logsource:
  product: windows
  service: dns-server
product: windows
references:
- https://medium.com/@esnesenon/feature-not-bug-dnsadmin-to-dc-compromise-in-one-line-a0f779b8dc83
- https://technet.microsoft.com/en-us/library/cc735829(v=ws.10).aspx
- https://twitter.com/gentilkiwi/status/861641945944391680
service: dns-server
status: experimental
tags:
- attack.defense_evasion
- attack.t1574.002
title: DNS Server Error Failed Loading the ServerLevelPluginDLL
