author: Jonathan Cheong, oscd.community
date: 2020/10/15
description: Detects Obfuscated use of stdin to execute PowerShell
detection:
  condition: selection and selection_eventid
  selection:
    winlog.event_data.ServiceFileName|re: .*cmd.{0,5}(?:\/c|\/r).+powershell.+(?:\$\{?input\}?|noexit).+\"
  selection_eventid:
    winlog.event_id: 4697
falsepositives:
- Unknown
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/17
product: windows
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 72862bf2-0eb1-11eb-adc1-0242ac120002
  type: derived
service: security
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation STDIN+ Launcher
