author: frack113
category: ps_script
date: 2022/08/19
definition: Script block logging must be enabled
description: Detect malicious GPO modifications can be used to implement many other
  malicious behaviors.
detection:
  condition: all of selection_*
  selection_key:
    winlog.event_data.ScriptBlockText|contains:
    - GroupPolicyRefreshTimeDC
    - GroupPolicyRefreshTimeOffsetDC
    - GroupPolicyRefreshTime
    - GroupPolicyRefreshTimeOffset
    - EnableSmartScreen
    - ShellSmartScreenLevel
  selection_path:
    winlog.event_data.ScriptBlockText|contains: \SOFTWARE\Policies\Microsoft\Windows\System
falsepositives:
- Legitimate use
id: b7216a7d-687e-4c8d-82b1-3080b2ad961f
level: medium
logsource:
  category: ps_script
  definition: Script block logging must be enabled
  product: windows
product: windows
references:
- https://github.com/redcanaryco/atomic-red-team/blob/40b77d63808dd4f4eafb83949805636735a1fd15/atomics/T1484.001/T1484.001.md
related:
- id: ada4b0c4-758b-46ac-9033-9004613a150d
  type: similar
status: experimental
tags:
- attack.defense_evasion
- attack.privilege_escalation
- attack.t1484.001
title: Modify Group Policy Settings - ScriptBlockLogging
