author: vitaliy0x1
date: 2020/01/21
description: Detects AWS Config Service disabling
detection:
  condition: selection_source
  selection_source:
    eventName:
    - DeleteDeliveryChannel
    - StopConfigurationRecorder
    eventSource: config.amazonaws.com
falsepositives:
- Valid change in AWS Config Service
id: 07330162-dba1-4746-8121-a9647d49d297
level: high
logsource:
  product: aws
  service: cloudtrail
modified: 2021/08/09
product: aws
service: cloudtrail
status: experimental
tags:
- attack.defense_evasion
- attack.t1562.001
title: AWS Config Disabling Channel/Recorder
