author: iwillkeepwatch
category: registry_event
date: 2019/01/18
description: Detects the addition of a SSP to the registry. Upon a reboot or API call,
  SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
detection:
  condition: selection_registry and not exclusion_images
  exclusion_images:
  - winlog.event_data.Image: C:\Windows\system32\msiexec.exe
  - winlog.event_data.Image: C:\Windows\syswow64\MsiExec.exe
  selection_registry:
    winlog.event_data.TargetObject:
    - HKLM\System\CurrentControlSet\Control\Lsa\Security Packages
    - HKLM\System\CurrentControlSet\Control\Lsa\OSConfig\Security Packages
falsepositives:
- Unlikely
id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
level: critical
logsource:
  category: registry_event
  product: windows
modified: 2020/09/06
product: windows
references:
- https://attack.mitre.org/techniques/T1101/
- https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
status: experimental
tags:
- attack.persistence
- attack.t1547.005
title: Security Support Provider (SSP) Added to LSA Configuration
