author: INIT_6
date: 2021/07/02
description: Detects remote printer driver load from Detailed File Share in Security
  logs that are a sign of successful exploitation attempts against print spooler vulnerability
  CVE-2021-1675 and CVE-2021-34527
detection:
  condition: selection
  selection:
    winlog.event_data.AccessMask: '0x3'
    winlog.event_data.ObjectType: File
    winlog.event_data.RelativeTargetName: spoolss
    winlog.event_data.ShareName: \\\*\IPC$
    winlog.event_id: '5145'
falsepositives:
- nothing observed so far
id: 8fe1c584-ee61-444b-be21-e9054b229694
level: critical
logsource:
  product: windows
  service: security
product: windows
references:
- https://twitter.com/INIT_3/status/1410662463641731075
- https://nvd.nist.gov/vuln/detail/cve-2021-1675
- https://nvd.nist.gov/vuln/detail/cve-2021-34527
service: security
status: experimental
tags:
- attack.execution
title: CVE-2021-1675 Print Spooler Exploitation IPC Access
