author: Austin Songer @austinsonger
date: 2021/09/12
description: Detects when an application is modified or deleted.
detection:
  condition: selection
  selection:
    eventtype:
    - application.lifecycle.update
    - application.lifecycle.delete
falsepositives:
- Unknown
id: 7899144b-e416-4c28-b0b5-ab8f9e0a541d
level: medium
logsource:
  product: okta
  service: okta
modified: 2021/09/22
product: okta
references:
- https://developer.okta.com/docs/reference/api/system-log/
- https://developer.okta.com/docs/reference/api/event-types/
service: okta
status: experimental
tags:
- attack.impact
title: Okta Application Modified or Deleted
